### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AtomicRobotMan0101**
Modified some of the text to aide in readability and remove the redundant duplication from my previous edits.

Happy to pass an eye over any new work, just pop me a message :)

### CODE REVIEW

**Comment by Jorman** [comment]
Ciao @AtomicRobotMan0101 
As always thanks for your help, I am not so good at creating pages of explanations!
What do you think about creating a usage page for the various scripts? Sort of like a wiki on the usage of each script.
Do you have any other ideas otherwise?

**Comment by AtomicRobotMan0101** [comment]
Perfection! 

Love to help with that. I can start immediately if you wish. 

I think a simple versioning system would be useful. It prob already exists (I'm on my phone, but when I'm on the dev machine I'll check). Something like yyyy.mm.increment

E.g. 2024.05.1 ... 2... 3

Just so users can easily determine if they have the latest scripts. Dev seems rapid this month! 😸😹😺

**Comment by Jorman** [comment]
Yep, is not a problem to put the version inside the script, just to be sure to work with the good one.
I'll put it on every script files, just start with version V1.00
This kind of script are "static" sometimes update when maybe new ideas or new functionality or maybe to fix little problems, so I don't want that some people think oh, is one old version just because they saw version 2022.04 on it

**Comment by AtomicRobotMan0101** [comment]
do I need to do anything to push this little bit live?

ill do the other doco this week.

**Comment by AtomicRobotMan0101** [comment]
prod prod....

**Review by Jorman — APPROVED** [review]

**Comment by Jorman** [comment]
Ciao @AtomicRobotMan0101 
Sorry for the long delay!
I saw that I already have wiki section, so maybe is better to "move" or implement that side, instead push all modification inside the main readme.md.
What do you think?

**Comment by AtomicRobotMan0101** [comment]
Hell yeah. 

I'm helping on [another project,](https://github.com/atuinsh/docs) which uses Astro: https://astro.build/

It can suck in [markdown documents](https://docs.astro.build/en/guides/markdown-content/) and burp them out. This way we can edit them on Github (or locally) and you can suck them into the publishing tool automagically: https://docs.astro.build/en/guides/content-collections/

It needs a domain, etc... which might be... problematic given the nature of this project :)

But happy to help do doco and split it all up - I absolutely agree its the right thing to do, for the sake of editing and adding some finesse. :)

**Pull request merged**
