### PR TITLE
Divided the Readme up into sections, with independent content.

### PR DESCRIPTION
**Pull request by AtomicRobotMan0101**
Might I suggest the archive be relabelled into something like "BitTorrent_management_scripts"

I'll edit the scripts to add headers next, then SEO up the content.... that will be PR 2 and 3.

After that, we can do the Wiki! w00t!

### CODE REVIEW

**Comment by AtomicRobotMan0101** [comment]
prod prod.

Going to start the wikis soon :)

**Comment by Jorman** [comment]
Ciao @AtomicRobotMan0101 
Sorry for the cosmic delay, I haven't been on git much lately! Thanks for your work, but how can we do it for the wiki and everything else? I am unfamiliar with git, I use it at 1% of its potential and do everything online, maybe there is a "faster" method?

**Comment by Jorman** [comment]
> Might I suggest the archive be relabelled into something like "BitTorrent_management_scripts"
> 
> I'll edit the scripts to add headers next, then SEO up the content.... that will be PR 2 and 3.
> 
> After that, we can do the Wiki! w00t!

It's just not just scripts for qBittorrent, maybe we can organize into folders? So each folder has within it the .md files and only the files dedicated to that project, if it is a project like qBittorrent. what do you think?

**Comment by AtomicRobotMan0101** [comment]
GIT is hideous, but its what we have so far.

Ive been distracted with some big things, back to it now. I'll do up the wiki.

**Review by Jorman — APPROVED** [review]

**Comment by Jorman** [comment]
here we go!

**Pull request merged**
